# configuration.yml

# configuration for the instrument package
# simple key:value pairs

DATABROKER_CATALOG: &databroker_catalog 1id_hexm  # can change this is assigned a new catalog

# default RunEngine metadata
# Very important to define this metadata!  If/when the same catalog is used
# by multiple instruments (1-ID-C, 1-ID,E, ...), this is the information
# that can identify which instrument collected the run.
# Without this information, it is extremely complicated to identify which instrument.
RUNENGINE_METADATA:
  beamline_id: 1-ID-C
  instrument_name: HEXM
  proposal_id: APSU-bdp2024
  databroker_catalog: *databroker_catalog

#APS Data management
DM_SETUP_FILE: "/home/dm/s1idge3dm/etc/dm.setup.sh"

# Experimental information (specific to BTR/PI)
EXPERIMENT:

  TITLE : Flyscan_BDP_Demo
  DESCRIPTION : "Demonstrate MPE fly scan using 20IDD aero stage and Varex."

  #Experimental folder appended to save paths
  PI_FOLDER: dev_jul24
  DM_EXPERIMENT_NAME : dev_jul24

  #HDF5 layout and attribute file paths moved to individual AD files! 

  #Select SMS
  SMS: aero_roty          #options: sms_aero, sms_lab, mts, owis, rams3

  #Select detector(s) and DMS(s)
  DETECTORS:

    DATA_COLLECTORS:
      imaging: null              #options: null, point_grey, grasshopper, retiga_tomo
      scattering: varex20idff    #options: null, hydra, GE5, pilatus, varex, retiga_nf, oryx
      saxs: null                 #options: null, pixirad
      other: null                #options: null, dic

    MOTOR_STACKS:
      imaging: null       #options: null, tomo_b, tomo_c, tomo_us_e, tomo_ds_e
      scattering: null    #options: null, hydra_positioner, det2_c, det2_e, nearfield, vff
      saxs: null          #options: null, saxs
      other: null         #options: null, four_circle

    HYDRA_PANELS: [ge1, ge2, ge3, ge4]  #order doesn't matter

  #Select sample environment
  SAMPLE_ENV: null        #options: null, cmu_furnace, rf_tube, am

  #MONITOR_CHANNELS #potentially for flyscan

ANALYSIS:
  dm_workflow_name : midas-ff
  analysis_subdir: analysis/hedm/ff_rec/
  analysis_workstations: [califone, polaris]
  num_cpus: 64
  num_frame_chunks: 100
  pre_proc_thresh : 80

  #MIDAS parameter file
  parameter_file: /home/beams/S20HEDM/ps_shade_au.txt

# ---------------------------------------------------

# Directory to "autosave" the RE.md dictionary (uses PersistentDict)
# Uncomment and modify to change from the default.
RUNENGINE_MD_PATH: /home/beams/S1IDTEST/.config/Bluesky_RunEngine_md/

#Permissions
# ALLOW_AREA_DETECTOR_WARMUP: true
# ENABLE_AREA_DETECTOR_IMAGE_PLUGIN: true
# ENABLE_CALCS: true
USE_PROGRESS_BAR: false
WRITE_SPEC_DATA_FILES: true

# Uncomment any of these to override the defaults
LOGGING:
  # MAX_BYTES: 1000000
  NUMBER_OF_PREVIOUS_BACKUPS: 9
  # LOG_PATH: /tmp
  # If LOG_PATH undefined, this session will log into PWD/logs/
  # where PWD is present working directory when session is started

# default timeouts (seconds)
PV_READ_TIMEOUT: &TIMEOUT 15
PV_WRITE_TIMEOUT: *TIMEOUT
PV_CONNECTION_TIMEOUT: *TIMEOUT

XMODE_DEBUG_LEVEL: Minimal

# Minimum software package version checks: MAJOR.minor (no .patch).
# These will be converted to tuple() for comparisons.
MINIMUM_PYTHON_VERSION:
  - 3
  - 8
MINIMUM_BLUESKY_VERSION:
  - 1
  - 10
MINIMUM_OPHYD_VERSION:
  - 1
  - 7
MINIMUM_DATABROKER_VERSION:
  - 1
  - 2
